#name: release-to-maven-central
#on:
#  workflow_dispatch:
#    inputs:
#      releaseversion:
#        description: 'Release version'
#        required: true
#        default: '2.4.0'
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up Maven Central Repository
#        uses: actions/setup-java@v3
#        with:
#          java-version: 1.8
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE
#
#      - name: Remove '-SNAPSHOT' from the version
#        run: mvn versions:set "-DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')"
#
#      - name: Publish package
#        run: mvn --file pom.xml -s release/m2-settings.xml --batch-mode clean deploy -P central-deploy -DskipTests=true
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}